baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[menu]
[[menu.main]]
  identifier = 'pages'
  name = 'Pages'
  url = '/pages/'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[permalinks]
  posts = '/posts/:year/:year-:month-:day-:slug/'
  tags = '/posts/:section/:slug/'
  pages = '/:sections[1:]/:slug/'